import PolicyLayout from "@/components/legal/policy-layout";

const LEGAL_ENTITY_NAME = "Gabriel Pereira, trading as Unsaid";
const PRIVACY_EMAIL = "legal@byunsaid.com";

const PrivacyPage = () => {
    return (
        <PolicyLayout title="Privacy Policy" lastUpdated="March 16, 2026">
            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    1. Introduction - Who We Are
                </h2>
                <p>
                    Unsaid is an AI-powered journaling application that helps
                    you understand your own thinking, emotions, and behaviour
                    through private, reflective writing. Unsaid is operated by{" "}
                    <strong>{LEGAL_ENTITY_NAME}</strong>, based in Portugal,
                    European Union.
                </p>
                <p className="mt-2">
                    This Privacy Policy explains what personal data we collect,
                    why we collect it, how we use it, who we share it with, how
                    long we keep it, and what rights you have over it.
                </p>
                <p className="mt-2">
                    We are the <strong>data controller</strong> for the personal
                    data described in this policy. Questions or data rights
                    requests: <strong>{PRIVACY_EMAIL}</strong>.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    2. What Data We Collect
                </h2>

                <p className="font-medium mt-4 mb-1">
                    2.1 Account and Identity Data.
                </p>
                <ul className="list-disc pl-5 space-y-1">
                    <li>Email address, username, internal Clerk user ID</li>
                    <li>Account role, subscription status, trial dates</li>
                    <li>Account creation and update timestamps</li>
                    <li>
                        A soft-delete timestamp (set on deletion request; data
                        permanently purged after 30 days)
                    </li>
                </ul>
                <p className="mt-2 text-sm text-muted-foreground">
                    Passwords are not stored by Unsaid - managed entirely by
                    Clerk.
                </p>

                <p className="font-medium mt-4 mb-1">2.2 Journal Entry Data.</p>
                <p>
                    All journal content is{" "}
                    <strong>encrypted with AES-GCM before storage</strong> - no
                    one with database access can read entries without the
                    encryption key.
                </p>
                <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>
                        Encrypted journal entry ciphertext (with IV and
                        authentication tag)
                    </li>
                    <li>Word count (a plain integer)</li>
                    <li>
                        A <strong>vector embedding</strong> (1,536
                        floating-point numbers generated by OpenAI
                        text-embedding-3-small) - used solely to power semantic
                        search within your own entries; cannot reconstruct
                        original text
                    </li>
                    <li>Entry timestamps</li>
                </ul>

                <p className="font-medium mt-4 mb-1">
                    2.3 AI-Generated Insights.
                </p>
                <p>
                    All AI-generated content is also encrypted at rest with
                    AES-GCM.
                </p>
                <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>
                        <strong>Tier 1 (per-entry):</strong> Encrypted
                        reflection generated by Anthropic Claude Haiku after
                        each entry is saved
                    </li>
                    <li>
                        <strong>Tier 2 (weekly patterns):</strong> Encrypted
                        pattern cards generated weekly by Anthropic Claude
                        Sonnet. Pattern types: theme, trigger, thought_pattern,
                        avoidance, habit, need, growth. Entry IDs analyzed are
                        stored.
                    </li>
                    <li>
                        <strong>Tier 3 (progress reports):</strong> Encrypted
                        progress report generated approximately every 15 entries
                        by Anthropic Claude Sonnet. Entry IDs analyzed are
                        stored.
                    </li>
                    <li>
                        <strong>Journaling prompts:</strong> AI-suggested
                        writing prompts (plaintext - these contain no journal
                        content)
                    </li>
                </ul>

                <p className="font-medium mt-4 mb-1">
                    2.4 Usage and Progress Data.
                </p>
                <ul className="list-disc pl-5 space-y-1">
                    <li>Total entry count (integer)</li>
                    <li>
                        Entry count at time of last progress report generation
                    </li>
                </ul>

                <p className="font-medium mt-4 mb-1">
                    2.5 Subscription and Billing Data.
                </p>
                <ul className="list-disc pl-5 space-y-1">
                    <li>
                        Subscription status, trial/billing period dates,
                        cancellation date
                    </li>
                    <li>
                        LemonSqueezy subscription ID and customer ID (internal
                        identifiers, not payment details)
                    </li>
                    <li>Plan name and price</li>
                    <li>Customer portal URL (for surfacing in app)</li>
                </ul>
                <p className="mt-2 text-sm text-muted-foreground">
                    Payment card details are never stored by Unsaid - handled
                    entirely by LemonSqueezy on PCI-DSS compliant
                    infrastructure.
                </p>

                <p className="font-medium mt-4 mb-1">
                    2.6 Payment Event Audit Log (Internal Only).
                </p>
                <p>
                    Full raw webhook payloads from LemonSqueezy are stored for
                    audit and idempotency purposes. These may include billing
                    name, address, and email as provided to LemonSqueezy at
                    checkout. Accessible only via service-role database
                    connection; never surfaced to any user.
                </p>

                <p className="font-medium mt-4 mb-1">2.7 Feedback Data.</p>
                <p>
                    If you submit a bug report or feature request via the in-app
                    feedback board: title, description, category, and status are
                    stored. Feedback is visible to other authenticated Unsaid
                    users on the feedback board. Upvotes are counted.
                </p>

                <p className="font-medium mt-4 mb-1">
                    2.8 Technical and Analytics Data.
                </p>
                <ul className="list-disc pl-5 space-y-1">
                    <li>
                        <strong>Vercel server logs:</strong> IP addresses, HTTP
                        headers, standard web server metadata - retained per
                        Vercel&rsquo;s retention policy
                    </li>
                    <li>
                        <strong>PostHog analytics:</strong> Pseudonymous usage
                        events (page views, feature usage).{" "}
                        <strong>
                            No journal content is included in any analytics
                            event.
                        </strong>{" "}
                        Runs on PostHog Cloud EU - data does not leave the EU.
                    </li>
                    <li>
                        <strong>Sentry error traces:</strong> Stack traces for
                        application errors, configured to exclude PII and
                        journal content
                    </li>
                </ul>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    3. How We Use Your Data - Purpose and Legal Basis
                </h2>
                <div className="overflow-x-auto mt-2">
                    <table className="w-full text-sm border-collapse">
                        <thead>
                            <tr className="border-b">
                                <th className="text-left py-2 pr-4 font-medium">
                                    Purpose
                                </th>
                                <th className="text-left py-2 pr-4 font-medium">
                                    Legal Basis (GDPR)
                                </th>
                            </tr>
                        </thead>
                        <tbody className="divide-y">
                            <tr>
                                <td className="py-2 pr-4">
                                    Create and manage your account
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(b) - contract
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Store and display journal entries
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(b) - contract
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Generate AI insights (all tiers)
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(b) - contract
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Generate vector embeddings for semantic
                                    search
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(b) - contract
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Manage subscription and process payments
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(b) - contract
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Send transactional emails
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(b) - contract
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Maintain payment audit log
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(f) - legitimate interest
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Understand usage and improve Unsaid
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(f) - legitimate interest
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Monitor and fix application errors
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(f) - legitimate interest
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Comply with legal obligations
                                </td>
                                <td className="py-2">
                                    Art. 6(1)(c) - legal obligation
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <p className="mt-4">
                    <strong>Special category data (GDPR Art. 9).</strong>{" "}
                    Journal entries may contain health-related or other
                    sensitive information. We do not solicit this data
                    deliberately. Our legal basis for any special category data
                    contained in entries is <strong>explicit consent</strong>{" "}
                    (Art. 9(2)(a)) - given by your act of using the service. You
                    may withdraw consent at any time by deleting your entries
                    and account.
                </p>
                <p className="mt-2">
                    We do not sell your data. We do not use your data for
                    advertising or third-party profiling.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    4. AI Processing - How Your Journal Text Is Used
                </h2>
                <p>
                    <strong>4.1 What happens when you save an entry</strong>
                </p>
                <p className="mt-2">
                    <strong>Step 1 - Sent to Anthropic.</strong> Your entry text
                    is sent over encrypted HTTPS to Anthropic&rsquo;s Claude
                    Haiku model, which returns a per-entry insight. Entry text
                    is not retained by Anthropic for training purposes under
                    their current API terms.
                </p>
                <p className="mt-2">
                    <strong>Step 2 - Sent to OpenAI.</strong> Your entry text is
                    sent over encrypted HTTPS to OpenAI&rsquo;s
                    text-embedding-3-small model, which returns a vector
                    embedding. The embedding is stored; the original text is not
                    retained by OpenAI for training purposes under their current
                    API terms.
                </p>
                <p className="mt-2">
                    <strong>Step 3 - Encrypted before storage.</strong> Both
                    your entry text and the AI insight are encrypted with
                    AES-GCM before being written to the database. No readable
                    copy is stored anywhere in our infrastructure. Decryption
                    occurs only in memory, on-demand, when you retrieve your
                    entries.
                </p>
                <p className="mt-4">
                    <strong>4.2 Weekly analysis (Tier 2).</strong> An automated
                    weekly job decrypts your entries in memory and sends them to
                    Anthropic Claude Sonnet to generate pattern cards. Results
                    are encrypted before storage.
                </p>
                <p className="mt-2">
                    <strong>4.3 Progress reports (Tier 3).</strong>{" "}
                    Approximately every 15 entries, an automated process
                    decrypts a selection of your entries in memory and sends
                    them to Anthropic Claude Sonnet for a longer-form progress
                    report. Results are encrypted before storage.
                </p>
                <p className="mt-4">
                    <strong>4.4 AI model training.</strong> Under
                    Anthropic&rsquo;s and OpenAI&rsquo;s API policies, data
                    submitted via API is not used to train their foundation
                    models. Review their current policies directly:
                </p>
                <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>
                        Anthropic:{" "}
                        <a
                            href="https://anthropic.com/legal/privacy"
                            className="underline"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            anthropic.com/legal/privacy
                        </a>
                    </li>
                    <li>
                        OpenAI:{" "}
                        <a
                            href="https://openai.com/policies/privacy-policy"
                            className="underline"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            openai.com/policies/privacy-policy
                        </a>
                    </li>
                </ul>
                <p className="mt-4">
                    <strong>4.5 Your choice.</strong> AI processing is central
                    to Unsaid. If you do not wish your journal text to be sent
                    to Anthropic or OpenAI, you should not use this service.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    5. Data Storage and Security
                </h2>
                <p>
                    <strong>5.1 Encryption at rest (AES-GCM).</strong> Journal
                    entries, per-entry insights, weekly pattern
                    descriptions/questions/experiments, and progress reports are
                    all encrypted with AES-GCM before database write. The
                    database stores only ciphertext. Unsaid engineers with
                    direct database access cannot read your journal content.
                </p>
                <p className="mt-2">
                    <strong>5.2 Row Level Security (RLS).</strong> Every
                    database query is constrained at the database engine level
                    to return only rows belonging to the currently authenticated
                    user. Application-layer bugs cannot expose one user&rsquo;s
                    data to another.
                </p>
                <p className="mt-2">
                    <strong>5.3 Encryption in transit (TLS).</strong> All data
                    in transit - between your browser and our servers, and
                    between our servers and any third party - is protected by
                    HTTPS/TLS.
                </p>
                <p className="mt-2">
                    <strong>5.4 Authentication security.</strong> Authentication
                    and session management are handled by Clerk (session tokens,
                    CSRF protection, secure cookies, MFA support). We do not
                    store passwords or session secrets.
                </p>
                <p className="mt-2">
                    <strong>5.5 Access controls.</strong> Direct database access
                    is restricted to the service-role connection and a very
                    small number of engineers. Payment event data is accessible
                    only via service-role database policies.
                </p>
                <p className="mt-2">
                    <strong>5.6 Breach notification.</strong> In the event of a
                    personal data breach, we will notify the CNPD within 72
                    hours (GDPR Art. 33). If the breach poses a high risk to
                    your rights, we will also notify you directly without undue
                    delay (GDPR Art. 34).
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    6. Third-Party Services and Sub-Processors
                </h2>
                <div className="overflow-x-auto mt-2">
                    <table className="w-full text-sm border-collapse">
                        <thead>
                            <tr className="border-b">
                                <th className="text-left py-2 pr-4 font-medium">
                                    Service
                                </th>
                                <th className="text-left py-2 pr-4 font-medium">
                                    Purpose
                                </th>
                                <th className="text-left py-2 pr-4 font-medium">
                                    Data Received
                                </th>
                                <th className="text-left py-2 font-medium">
                                    Location
                                </th>
                            </tr>
                        </thead>
                        <tbody className="divide-y">
                            <tr>
                                <td className="py-2 pr-4">Clerk</td>
                                <td className="py-2 pr-4">Authentication</td>
                                <td className="py-2 pr-4">
                                    Email, name, Google OAuth profile
                                </td>
                                <td className="py-2">US (SCCs)</td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">Anthropic</td>
                                <td className="py-2 pr-4">
                                    AI insights (Tier 1, 2, 3)
                                </td>
                                <td className="py-2 pr-4">
                                    Journal entry text, decrypted at generation
                                    time
                                </td>
                                <td className="py-2">US (SCCs)</td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">OpenAI</td>
                                <td className="py-2 pr-4">Vector embeddings</td>
                                <td className="py-2 pr-4">
                                    Journal entry text, decrypted at generation
                                    time
                                </td>
                                <td className="py-2">US (SCCs)</td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">Supabase</td>
                                <td className="py-2 pr-4">
                                    PostgreSQL database
                                </td>
                                <td className="py-2 pr-4">
                                    All user data (journal content encrypted)
                                </td>
                                <td className="py-2">EU</td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">Vercel</td>
                                <td className="py-2 pr-4">
                                    Application hosting
                                </td>
                                <td className="py-2 pr-4">
                                    Server logs, request metadata
                                </td>
                                <td className="py-2">US + EU Edge</td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">PostHog</td>
                                <td className="py-2 pr-4">Product analytics</td>
                                <td className="py-2 pr-4">
                                    Pseudonymous usage events (no journal
                                    content)
                                </td>
                                <td className="py-2">EU</td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">Resend</td>
                                <td className="py-2 pr-4">
                                    Transactional email
                                </td>
                                <td className="py-2 pr-4">
                                    Email address, first name
                                </td>
                                <td className="py-2">US (SCCs)</td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">Sentry</td>
                                <td className="py-2 pr-4">Error monitoring</td>
                                <td className="py-2 pr-4">
                                    Error traces (no PII, no journal content)
                                </td>
                                <td className="py-2">US (SCCs)</td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">LemonSqueezy</td>
                                <td className="py-2 pr-4">
                                    Payment processing
                                </td>
                                <td className="py-2 pr-4">
                                    Name, email, billing address, payment
                                    metadata
                                </td>
                                <td className="py-2">US (SCCs)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <p className="mt-4 text-sm">
                    None of these parties are permitted to use your data for any
                    purpose other than providing their service to us.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    7. International Data Transfers
                </h2>
                <p>
                    Unsaid is operated from Portugal (EU). Several
                    sub-processors are US-based. Where the EU-US Data Privacy
                    Framework does not apply, we rely on{" "}
                    <strong>Standard Contractual Clauses (SCCs)</strong>{" "}
                    approved by the European Commission under GDPR Art.
                    46(2)(c). PostHog and Supabase process data within the EU
                    and it does not leave the EU.
                </p>
                <p className="mt-2">
                    Contact {PRIVACY_EMAIL} for information about specific
                    safeguards for any processor.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">8. Data Retention</h2>
                <div className="overflow-x-auto mt-2">
                    <table className="w-full text-sm border-collapse">
                        <thead>
                            <tr className="border-b">
                                <th className="text-left py-2 pr-4 font-medium">
                                    Data Category
                                </th>
                                <th className="text-left py-2 pr-4 font-medium">
                                    Retention
                                </th>
                                <th className="text-left py-2 font-medium">
                                    Reason
                                </th>
                            </tr>
                        </thead>
                        <tbody className="divide-y">
                            <tr>
                                <td className="py-2 pr-4">
                                    Account and identity data
                                </td>
                                <td className="py-2 pr-4">
                                    Duration of account + 30 days after deletion
                                </td>
                                <td className="py-2">
                                    Service provision; brief recovery window
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Journal entries (encrypted)
                                </td>
                                <td className="py-2 pr-4">
                                    Duration of account; permanently deleted on
                                    account deletion
                                </td>
                                <td className="py-2">
                                    No basis for retention after deletion
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    AI-generated insights (encrypted)
                                </td>
                                <td className="py-2 pr-4">
                                    Duration of account; permanently deleted on
                                    account deletion
                                </td>
                                <td className="py-2">
                                    Derived entirely from entries
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Subscription and billing data
                                </td>
                                <td className="py-2 pr-4">
                                    Duration of account + 30 days
                                </td>
                                <td className="py-2">
                                    Legal basis; dispute resolution
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Payment event audit log
                                </td>
                                <td className="py-2 pr-4">
                                    <strong>7 years</strong> from payment date
                                </td>
                                <td className="py-2">
                                    Legal obligation - Portuguese/EU tax law
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    PostHog analytics events
                                </td>
                                <td className="py-2 pr-4">
                                    Up to 7 years (pseudonymous, no journal
                                    content)
                                </td>
                                <td className="py-2">
                                    Long-term product analytics
                                </td>
                            </tr>
                            <tr>
                                <td className="py-2 pr-4">
                                    Sentry error traces
                                </td>
                                <td className="py-2 pr-4">90 days</td>
                                <td className="py-2">Bug resolution</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <p className="mt-4">
                    <strong>Account deletion:</strong> Soft-delete flag is set
                    immediately on request, disabling access. After 30 days, all
                    journal entries, ciphertext, vector embeddings, AI insights,
                    and user profile are{" "}
                    <strong>permanently and irreversibly deleted</strong> via
                    cascading database delete. Payment event records are
                    retained separately as required by law.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">9. Your Rights</h2>
                <p className="font-medium mb-2">
                    9.1 GDPR rights (EEA, UK, Switzerland)
                </p>
                <ul className="list-disc pl-5 space-y-2">
                    <li>
                        <strong>Access (Art. 15):</strong> Request a copy of
                        your personal data and how it is processed.
                    </li>
                    <li>
                        <strong>Rectification (Art. 16):</strong> Correct
                        inaccurate or incomplete data. Update email/username in
                        account settings directly.
                    </li>
                    <li>
                        <strong>Erasure (Art. 17):</strong> Delete your account
                        from within the app (triggers permanent purge as
                        described in Section 8). For legally retained data, we
                        will explain why and confirm when retention is no longer
                        required.
                    </li>
                    <li>
                        <strong>Restriction (Art. 18):</strong> Request
                        restriction of processing to storage only while
                        contesting accuracy or objecting.
                    </li>
                    <li>
                        <strong>Portability (Art. 20):</strong> Receive your
                        journal entries and AI insights in a structured,
                        machine-readable format for transfer to another
                        controller.
                    </li>
                    <li>
                        <strong>Object (Art. 21):</strong> Object to processing
                        based on legitimate interests (analytics, error
                        monitoring). We will cease unless we can demonstrate
                        compelling legitimate grounds.
                    </li>
                    <li>
                        <strong>Withdraw consent (Art. 7(3)):</strong> Withdraw
                        consent for special category data at any time by
                        deleting your entries and account.
                    </li>
                    <li>
                        <strong>Automated decisions (Art. 22):</strong> Unsaid
                        does not make legally significant automated decisions
                        about you. AI insights are for personal reflection only.
                    </li>
                </ul>

                <p className="font-medium mt-4 mb-2">
                    9.2 Right to lodge a complaint
                </p>
                <div className="border rounded-lg p-4 text-sm">
                    <p className="font-medium">
                        Comissão Nacional de Proteção de Dados (CNPD)
                    </p>
                    <p>Av. D. Carlos I, 134, 1.º - 1200-651 Lisboa, Portugal</p>
                    <a
                        href="https://www.cnpd.pt"
                        className="underline"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        www.cnpd.pt
                    </a>
                </div>
                <p className="mt-2 text-sm">
                    You may also complain to the supervisory authority in your
                    country of residence. We ask that you contact us at{" "}
                    {PRIVACY_EMAIL} first so we can resolve it directly.
                </p>

                <p className="font-medium mt-4 mb-2">
                    9.3 CCPA rights (California residents)
                </p>
                <ul className="list-disc pl-5 space-y-1">
                    <li>
                        <strong>Right to know:</strong> Categories and specific
                        pieces of personal information collected, sources,
                        purposes, and third parties shared with.
                    </li>
                    <li>
                        <strong>Right to delete:</strong> Request deletion,
                        subject to legal retention obligations.
                    </li>
                    <li>
                        <strong>Right to correct:</strong> Request correction of
                        inaccurate information.
                    </li>
                    <li>
                        <strong>Right to opt out of sale/sharing:</strong> We{" "}
                        <strong>
                            do not sell or share personal information
                        </strong>
                        . There is nothing to opt out of.
                    </li>
                    <li>
                        <strong>Right to limit sensitive data use:</strong> We
                        use journal content solely for the core features you
                        signed up for.
                    </li>
                    <li>
                        <strong>Non-discrimination:</strong> Exercising CCPA
                        rights will not affect your access to the service.
                    </li>
                </ul>

                <p className="font-medium mt-4 mb-2">
                    9.4 How to exercise rights
                </p>
                <p>
                    Email <strong>{PRIVACY_EMAIL}</strong> with subject line{" "}
                    <strong>&ldquo;Data Subject Request&rdquo;</strong>. Include
                    the email address on your account. We respond within 30 days
                    (GDPR) or 45 days (CCPA).
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    10. Cookies and Analytics
                </h2>
                <p>
                    <strong>
                        Authentication cookies (Clerk) - strictly necessary.
                    </strong>{" "}
                    Maintain your login session. Cannot be disabled if you want
                    to use the app.
                </p>
                <p className="mt-2">
                    <strong>Analytics cookies (PostHog) - analytics.</strong>{" "}
                    Pseudonymous identifier to understand feature usage and
                    improve the product. No journal content is ever included.
                    Data stays within the EU (PostHog Cloud EU).
                </p>
                <p className="mt-2">
                    We do not use advertising cookies or third-party tracking
                    cookies.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    11. Children&rsquo;s Privacy
                </h2>
                <p>
                    Unsaid is not intended for use by anyone under 18 years of
                    age. We do not knowingly collect personal data from
                    children. If we learn we have collected data from a person
                    under 18, we will delete it promptly. Contact{" "}
                    {PRIVACY_EMAIL} if you believe this has occurred.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">
                    12. Changes to This Policy
                </h2>
                <p>
                    We may update this Privacy Policy. For material changes, we
                    will post the updated policy and send email notification at
                    least <strong>14 days before</strong> the changes take
                    effect. Continued use after the effective date constitutes
                    acceptance.
                </p>
            </section>

            <section>
                <h2 className="font-semibold mt-6 mb-2">13. Contact Us</h2>
                <p>{LEGAL_ENTITY_NAME}</p>
                <p>
                    Email: <strong>{PRIVACY_EMAIL}</strong>
                </p>
                <p className="mt-2">
                    For data rights requests, use subject line{" "}
                    <strong>&ldquo;Data Subject Request&rdquo;</strong>.
                </p>
                <p className="mt-4">
                    <strong>Supervisory Authority:</strong> Comissão Nacional de
                    Proteção de Dados (CNPD) -{" "}
                    <a
                        href="https://www.cnpd.pt"
                        className="underline"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        www.cnpd.pt
                    </a>
                </p>
            </section>
        </PolicyLayout>
    );
};

export default PrivacyPage;
